version: '3.9'

services:
  db:
    container_name: music_db
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - .local/services/db:/var/lib/postgresql/data
    init: true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  webapp:
    build:
      context: .
    container_name: user_management_webapp
    image: music-service-app:latest
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - "5000:8000"
    volumes:
      - .:/src
    init: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
