version: '3.9'

services:

  webapp:
    build:
      context: .
    container_name: user_management_webapp
    image: music-service-app:latest
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - "5000:8000"
    volumes:
      - .:/src
    init: true
    restart: always
