name: ci
on: pull_request

jobs:

  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: set envs
        run: cp .env.sample .env

      - name: Build image
        run: docker-compose build webapp --no-cache

  lint:
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Run linters
        run: docker-compose run --rm webapp sh -c "flake8 && black . --check && isort . --check"
